model: ResNet18
pretrained: False 
load_from_path: False
model_path: ./trained_models/ResNet18_MNIST.pth'

input_shape: [1, 28, 28]
num_classes: 10

size: [16, 32]
kernel_size: [3, 3]
stride: [1, 1]
padding: [0, 0]
dropout: [0, 0]

dataset: MNIST

save_model: True
save_path: ./trained_models/ResNet18_MNIST.pth