seed: 19
batch_size: 64
epochs: 5
learning_rate: 0.001
device: cuda
multiprocess: False

temperature: 20
distillation_weight: 1
ce_weight: 0

teacher_model_config: configs/model_configs/ResNet101_CIFAR10.yaml
student_model_config: configs/model_configs/ResNet18_CIFAR10.yaml

dataset: CIFAR10

log_dir: ./logs/student-ResNet101-ResNet18-CIFAR10-CIFAR10-varied-0.001-5