model: ResNet18
pretrained: False 
load_from_path: False
model_path: ('./trained_models/ResNet18.pth',)

input_shape: [3, 32, 32]
num_classes: 10

size: [16, 32]
kernel_size: [3, 3]
stride: [1, 1]
padding: [0, 0]
dropout: [0, 0]

dataset: CIFAR10

save_model: True
save_path: ./trained_models/ResNet18_CIFAR10.pth