model_config: "configs/model_configs/ResNet101_MNIST.yaml" 
dataset_config: "configs/dataset_configs/MNIST.yaml"
device: "cuda"
size: 1000
total_size: 120_000

# the number of iterations for generating a single image
iterations: 10000

# didn't load the following 
output_dir: "data/synthetic"
save_to_dir: True
