model_config: "configs/model_configs/ResNet101_CIFAR10.yaml"
dataset_config: "configs/dataset_configs/CIFAR10.yaml"
device: "cuda"
size: 80
total_size: 80

# the number of iterations for generating a single image
iterations: 1000

# didn't load the following 
output_dir: "data/synthetic"
save_to_dir: True
