# general training parameters
seed: 19
batch_size: 32
epochs: 2
learning_rate: 0.001
device: cuda

# KD papermeters
temperature: 1
distillation_weight: 0.5
ce_weight: 0.5

# model parameters
teacher_model: custom
student_model: custom
pretraiend: 

# dataset parameters
dataset: MNIST

# should be c x h x w
shape: [1, 28, 28]
num_classes: 10


log_dir: "./logs"
